// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuwL6Hgzkz04RvhQd_vAEsyPJWhzi1PSg',
    appId: '1:834850251245:web:f12fe7c959f8852069c7e4',
    messagingSenderId: '834850251245',
    projectId: 'ofoq-games',
    authDomain: 'ofoq-games.firebaseapp.com',
    storageBucket: 'ofoq-games.firebasestorage.app',
    measurementId: 'G-H6D0G4PGWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc7oQliP4-PtKcPhYb5BLsmHByvuxBd-c',
    appId: '1:834850251245:android:7b9e97486fca9fe569c7e4',
    messagingSenderId: '834850251245',
    projectId: 'ofoq-games',
    storageBucket: 'ofoq-games.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfpNJd7epyXEfEpR2hldYYkpPKvaU5KNo',
    appId: '1:834850251245:ios:14c1fbd3279cab8d69c7e4',
    messagingSenderId: '834850251245',
    projectId: 'ofoq-games',
    storageBucket: 'ofoq-games.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfpNJd7epyXEfEpR2hldYYkpPKvaU5KNo',
    appId: '1:834850251245:ios:14c1fbd3279cab8d69c7e4',
    messagingSenderId: '834850251245',
    projectId: 'ofoq-games',
    storageBucket: 'ofoq-games.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuwL6Hgzkz04RvhQd_vAEsyPJWhzi1PSg',
    appId: '1:834850251245:web:69d7178ec0e7310669c7e4',
    messagingSenderId: '834850251245',
    projectId: 'ofoq-games',
    authDomain: 'ofoq-games.firebaseapp.com',
    storageBucket: 'ofoq-games.firebasestorage.app',
    measurementId: 'G-88L0Z7T3DE',
  );
}
